//Header file: tireModel.h
#ifndef TIRE_MODEL_H
#define TIRE_MODEL_H

#include "lateralDynamics.h"

//Structure for tire parameters
typedef struct 
{
    float   mu;
    float   stiffnessFactor;
    float   shapeFactor;
    float   peakForce;
} TireParameters;


//Structure for tire inputs
//1 -> Slip Angle in rad
//2 -> Normal force in N
typedef struct
{
    float   slipAngle;      //Tire's slip angle in radians
    float   normalForce;    //Normal force acting on the tire in Newton
} TireInputs;

typedef struct 
{
    float   lateralForce;   //Lateral force generated by the tire in Newton
    float   longForce;      //Longitudinal Force generated by the tire in Newton
} TireOutputs;

typedef struct 
{
    float   lateralForceFrontInner;     //Lateral force generated by the front inner tire in Newton
    float   lateralForceFrontOuter;     //Lateral force generated by the front outer tire in Newton
    float   lateralForceRearInner;      //Lateral force generated by the rear inner tire in Newton
    float   lateralForceRearOuter;      //Lateral force generated by the rear outer tire in Newton
    float   longitudinalForceFrontInner;    //Longitudinal force generated by the front inner tire in Newton
    float   longitudinalForceFrontOuter;    //Longitudinal force generated by the front outer tire in Newton
    float   longitudinalForceRearInner;     //Longitudinal force generated by the rear inner tire in Newton
    float   longitudinalForceRearOuter;     //Longitudinal force generated by the rear outer tire in Newton
} VehicleTireOutputs;


//Functions for calculating tire forces
void    calculateTireForces(const TireParameters *param,const TireInputs *inputs, TireOutputs *outputs);
void    calculateVehicleTireForces(const TireParameters *param, const LateralDynamics *latDyn, TireInputs *inputs, VehicleTireOutputs *output, TireOutputs *tireOutput)

#endif
