//Header file: tireModel.h
#ifndef TIRE_MODEL_H
#define TIRE_MODEL_H

//Structure for tire parameters
typedef struct 
{
    float   mu;
    float   stiffnessFactor;
    float   shapeFactor;
} TireParameters;


//Structure for tire inputs
//1 -> Slip Angle in rad
//2 -> Normal force in N
typedef struct
{
    float   slipAngle;      //Tire's slip angle in radians
    float   normalForce;    //Normal force acting on the tire in Newton
} TireInputs;

typedef struct 
{
    float   lateralForce;   //Lateral force generated by the tire in Newton
    float   longForce;      //Longitudinal Force generated by the tire in Newton
} TireOutputs;

//Functions for calculating tire forces
void    calculateTireForces(const TireParameters *param,const TireInputs *inputs, TireOutputs *outputs);

#endif
